name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t my-python-app .
      - name: Run tests
        run: docker run my-python-app pytest --cov=./ --cov-report=xml
      - name: Print coverage report
        run: docker run my-python-app coverage report
